# Generated by Django 4.2.4 on 2023-09-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses_enrolled',
            field=models.ManyToManyField(related_name='enrolled_students', to='instructors.course'),
        ),
    ]
