# Generated by Django 4.2.4 on 2023-09-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        ('students', '0002_student_courses_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_modules',
            field=models.ManyToManyField(blank=True, to='instructors.module'),
        ),
    ]
