# Generated by Django 4.2.4 on 2023-09-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_alter_course_created_at_alter_course_updated_at'),
        ('students', '0003_student_completed_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses_liked',
            field=models.ManyToManyField(blank=True, to='instructors.course'),
        ),
    ]
