# Generated by Django 4.0.5 on 2023-09-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_module_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='catagory',
            new_name='category',
        ),
    ]
